Repository quantum-ods/qmlcourse, pull requests merged in 2021-09, with the labels that each got.

#154 add back changes from #139, #140, and #147 (smth screwed)
  qmlcourseRU/_static/pythonblock/oop_l10/class_and_obj1.png
  qmlcourseRU/_static/pythonblock/oop_l10/class_and_obj_house.png
  qmlcourseRU/_static/pythonblock/oop_l10/class_and_obj_pika.png
  qmlcourseRU/book/pythonblock/python_l10.md
  qmlcourseRU/book/pythonblock/python_l4.md
  qmlcourseRU/book/pythonblock/python_l5.md
Labels: bug

#155 Update and modify program
  qmlcourseRU/_static/index/program.plantuml
  qmlcourseRU/_static/index/program.png
Labels: enhancement

#161 Немного обновил README
  README.md
Labels: documentation

#124 Python Intro lec6 (about lists and loops)
  qmlcourseRU/_static/pythonblock/list_loops_l6/list_indexing_1.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/pythonblock/python_l6.md
Labels: lecture

#162 Python lec11 outro
  qmlcourseRU/_static/pythonblock/python_l11/cats_show_love_differently.jpeg
  qmlcourseRU/_static/pythonblock/python_l11/debug_hard.png
  qmlcourseRU/_static/pythonblock/python_l11/debug_solved.png
  qmlcourseRU/_static/pythonblock/python_l11/example_debug.png
  qmlcourseRU/_static/pythonblock/python_l11/example_traceback.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/pythonblock/python_l11.md
Labels: lecture

#153 lec9 – python functions
  qmlcourseRU/_static/pythonblock/functions_l9/legb.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/pythonblock/python_l9.md
Labels: lecture

#151 Python intro lec7 about dicts
  .yaspellerrc.json
  qmlcourseRU/_static/pythonblock/dicts_l7/Python-Immutable-Example-1.png
  qmlcourseRU/_static/pythonblock/dicts_l7/Python-Immutable-Example-2.png
  qmlcourseRU/_static/pythonblock/dicts_l7/Python-Mutable-Example-2.png
  qmlcourseRU/_static/pythonblock/dicts_l7/Python-Mutable-Example.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/pythonblock/python_l6.md
  qmlcourseRU/book/pythonblock/python_l7.md
Labels: lecture

#177 обновил название файловое для python лекций после 7 и добавил немного слова для игнора
  .github/workflows/book-check-text.yml
  .github/workflows/pre-commit-deploy-book.yml
  .pre-commit-config.yaml
  .yaspellerrc.json
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/mlblock/ml_l1.md
  qmlcourseRU/book/pythonblock/python_l10.md
  qmlcourseRU/book/pythonblock/python_l11.md
  qmlcourseRU/book/pythonblock/python_l8.md
  qmlcourseRU/book/pythonblock/python_l9.md
Labels: ci
