Repository quantum-ods/qmlcourse, pull requests merged in 2021-11, with the labels that each got.

#259 Feature/cicd aws
  .github/workflows/deploy-branch.yml
Labels: enhancement, ci

#247 [WIP] Lecture/linalgblock - by Alexey Pronkin
  .yaspellerrc.json
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/authors.md
  qmlcourseRU/book/glossary.md
  qmlcourseRU/book/index.md
  qmlcourseRU/book/linalgblock/algebra.md
  qmlcourseRU/book/linalgblock/bra-ket.md
  qmlcourseRU/book/linalgblock/intro.md
  qmlcourseRU/book/prerequisite.md
  qmlcourseRU/book/qcblock/gates.md
  qmlcourseRU/book/qcblock/qubit.md
Labels: lecture

#213 [WIP] lecture/Simon algorithm
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/qcalgo/simon_algorithm/simon_algo_circuit.png
  qmlcourseRU/_static/qcalgo/simon_algorithm/simon_principal.svg
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/authors.md
  qmlcourseRU/book/qcalgo/simon_algorithm.md
Labels: lecture

#263 Schmidt decomposition
  .yaspellerrc.json
  qmlcourseRU/_static/qcalgo/simon_algorithm/simon_algo_circuit.png
  qmlcourseRU/_static/qcalgo/simon_algorithm/simon_principal.svg
  qmlcourseRU/book/intro1block/intro1.md
  qmlcourseRU/book/qcalgo/simon_algorithm.md
  qmlcourseRU/book/qcblock/mixedstates.md
  qmlcourseRU/book/qcblock/qubit.md
  qmlcourseRU/book/qnnblock/qconv.ipynb
Labels: lecture, minor_fix

#228 Ising model
  .yaspellerrc.json
  pyproject.toml
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/problemsblock/advising/Ernst_Ising.png
  qmlcourseRU/_static/problemsblock/ising/Max-cut.png
  qmlcourseRU/_static/problemsblock/ising/af_ordering.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/authors.md
  qmlcourseRU/book/problemsblock/advising.md
  qmlcourseRU/book/problemsblock/ising.md
  qmlcourseRU/book/progblock/cirq_tfq.md
  qmlcourseRU/book/qnnblock/qconv.ipynb
Labels: lecture

#266 return the disappeared Simon's lecture
  qmlcourseRU/_static/simon_algo_circuit.png
  qmlcourseRU/_static/simon_principal.svg
  qmlcourseRU/book/qcalgo/simon_algorithm.md
Labels: bug, Hot, lecture

#267 replace a .svg with png
  qmlcourseRU/_static/qcalgo/simon_algorithm/simon_principal.png
  qmlcourseRU/book/qcalgo/simon_algorithm.md
Labels: minor_fix

#269 update authors page
  README.md
  qmlcourseRU/book/authors.md
Labels: minor_fix

#273 Виды квантового машинного обучения
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/qmlkindsblock/qmlkinds/C-GAN.png
  qmlcourseRU/_static/qmlkindsblock/qmlkinds/CNN_over_psi.png
  qmlcourseRU/_static/qmlkindsblock/qmlkinds/NQS.png
  qmlcourseRU/_static/qmlkindsblock/qmlkinds/PauliNet.png
  qmlcourseRU/_static/qmlkindsblock/qmlkinds/Qml_approaches.png
  qmlcourseRU/_static/qmlkindsblock/qmlkinds/RNN.png
  qmlcourseRU/_static/qnnblock/qnntfq.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/qmlkindsblock/qmlkinds.md
  qmlcourseRU/book/qmlkindsblock/qmlkindsintro.md
Labels: lecture

#274 Исправление опечатки в коде алгоритма Дойча
  qmlcourseRU/book/qcalgo/deutschs_algorithm.md
Labels: minor_fix

#270 [WIP] QKNN
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/qmlkindsblock/qknn/qknn.png
  qmlcourseRU/_static/qmlkindsblock/qknn/swap_test.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/qmlkindsblock/qknn.md
Labels: lecture

#187 Лекция по классическому SVM
  .yaspellerrc.json
  qmlcourseRU/_static/index/program.svg
  qmlcourseRU/_static/qcalgo/simon_algorithm/simon_algo_circuit.png
  qmlcourseRU/_static/qcalgo/simon_algorithm/simon_principal.svg
  qmlcourseRU/_static/qsvmblock/classicsvm/distance_to_the_plane.png
  qmlcourseRU/_static/qsvmblock/classicsvm/lin_classifier.png
  qmlcourseRU/_static/qsvmblock/classicsvm/linclass_margins.png
  qmlcourseRU/_static/qsvmblock/classicsvm/loss_functions_logistic_and_hinge.png
  qmlcourseRU/_static/qsvmblock/classicsvm/margin_toy_example.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/index.md
  qmlcourseRU/book/qsvmblock/classic_svm.md
  qmlcourseRU/book/qsvmblock/hybridsvm.md
  qmlcourseRU/book/qsvmblock/qsvmintro.md
Labels: lecture

#289 SVM – мелкие фиксы вдогонку
  qmlcourseRU/_static/qsvmblock/distance_to_the_plane.png
  qmlcourseRU/_static/qsvmblock/hybridsvm/Support_vector_machine.jpg
  qmlcourseRU/_static/qsvmblock/kernel_trick_idea.png
  qmlcourseRU/_static/qsvmblock/lin_classifier.png
  qmlcourseRU/_static/qsvmblock/linclass_margins.png
  qmlcourseRU/_static/qsvmblock/loss_functions_logistic_and_hinge.png
  qmlcourseRU/_static/qsvmblock/margin_toy_example.png
  qmlcourseRU/book/qsvmblock/classic_svm.md
  qmlcourseRU/book/qsvmblock/hybridsvm.md
Labels: minor_fix

#290 Мелкие фиксы
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/glossary.md
  qmlcourseRU/book/index.md
  qmlcourseRU/book/linalgblock/bra-ket.md
  qmlcourseRU/book/problemsblock/advising.md
  qmlcourseRU/book/problemsblock/ising.md
  qmlcourseRU/book/progblock/progreview.md
  qmlcourseRU/book/progblock/qiskit.md
  qmlcourseRU/book/pythonblock/python_l1.md
  qmlcourseRU/book/pythonblock/python_l2.md
  qmlcourseRU/book/pythonblock/python_l4.md
  qmlcourseRU/book/qcalgo/quantum_algorithms_overview.md
  qmlcourseRU/book/qcblock/mixedstates.md
  qmlcourseRU/book/qmlkindsblock/qknn.md
  qmlcourseRU/book/qmlkindsblock/qmlkinds.md
  qmlcourseRU/book/qnnblock/qconv.ipynb
  qmlcourseRU/book/qnnblock/qconv.md
  qmlcourseRU/book/qnnblock/qnn.md
Labels: enhancement, minor_fix

#283 Добавка в лекции про D-Wave (кв. хим)
  .yaspellerrc.json
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/dwaveblock/dwave/fig_4.png
  qmlcourseRU/_static/dwaveblock/dwave/fig_5.png
  qmlcourseRU/book/dwaveblock/dwave.md
Labels: lecture

#281 Lecture/combopt
  .yaspellerrc.json
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/problemsblock/copt/Hamilton.jpg
  qmlcourseRU/_static/problemsblock/copt/Knapsack.png
  qmlcourseRU/_static/problemsblock/copt/bridges.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/problemsblock/copt.md
  qmlcourseRU/book/problemsblock/problemsintro.md
Labels: lecture

#296 Fix workflow to install psi4 with conda into poetry venv
  .github/workflows/deploy-book.yml
  .github/workflows/deploy-branch.yml
  qmlcourseRU/book/problemsblock/quantchemadvancedscf.md
Labels: ci
