Repository quantum-ods/qmlcourse, pull requests merged in 2021-12, with the labels that each got.

#305 Добавлены отображение расчитываемых векторов и матриц для примеров в лекцию по кубитам
  qmlcourseRU/book/qcblock/qubit.md
Labels: enhancement

#307 ipynb -> md
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/problemsblock/copt.md
  qmlcourseRU/book/progblock/pennylane.ipynb
  qmlcourseRU/book/progblock/pennylane.md
  qmlcourseRU/book/progblock/progreview.md
Labels: minor_fix

#309 Lecture/formules 4 qubit measurement
  qmlcourseRU/book/authors.md
  qmlcourseRU/book/qcblock/qubit.md
Labels: enhancement, lecture

#212 [WIP] JW lecture
  .yaspellerrc.json
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/problemsblock/jordanwigner/encoding.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/problems2qml/jordanwigner.md
Labels: lecture

#308 np2ising
  .gitignore
  .yaspellerrc.json
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/problems2qml/np2ising.md
  qmlcourseRU/book/problems2qml/problems2qmlintro.md
Labels: lecture

#312 Lecture/eigenvals
  .yaspellerrc.json
  poetry.lock
  pyproject.toml
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/problems2qml/eigenvals/Mona_Lisa.png
  qmlcourseRU/_static/problems2qml/eigenvals/NQS.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/problems2qml/eigenvals.md
Labels: lecture

#196 VQE
  .yaspellerrc.json
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/problemsblock/ising/Max-cut.png
  qmlcourseRU/_static/problemsblock/ising/af_ordering.png
  qmlcourseRU/_static/vqeblock/vqe/HWA.png
  qmlcourseRU/_static/vqeblock/vqe/Mona_Lisa.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/progblock/cirq_tfq.md
  qmlcourseRU/book/vqeblock/tspvqe.md
  qmlcourseRU/book/vqeblock/vqe.md
  qmlcourseRU/book/vqeblock/vqeintro.md
Labels: lecture

#322 Added sitemap
  poetry.lock
  pyproject.toml
  qmlcourseRU/_config.yml
Labels: ci, seo

#323 Более короткая ссылка
  .github/workflows/deploy-book.yml
Labels: ci, seo

#325 Lecture/superdense_coding
  qmlcourseRU/_static/qcalgo/superdense_coding/Superdense_coding_wikimedia.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/qcalgo/quantum_teleportation.md
  qmlcourseRU/book/qcalgo/superdense_coding.md
Labels: lecture

#324 grammar + multiple fixes
  qmlcourseRU/_static/problemsblock/ising/Max-cut.png
  qmlcourseRU/_static/problemsblock/ising/af_ordering.png
  qmlcourseRU/book/problems2qml/eigenvals.md
  qmlcourseRU/book/problems2qml/np2ising.md
  qmlcourseRU/book/problems2qml/problems2qmlintro.md
  qmlcourseRU/book/problemsblock/ising.md
  qmlcourseRU/book/progblock/cirq_tfq.md
  qmlcourseRU/book/vqeblock/tspvqe.md
Labels: enhancement, minor_fix

#327 блок по перспективам
  qmlcourseRU/_static/perspectives/back_4_youtube.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/perspectives/academic_industrial.md
Labels: lecture

#331 Update sitemap.xml
  .github/workflows/deploy-book.yml
  poetry.lock
  pyproject.toml
  tools/fix_sitemap.py
Labels: ci, seo

#257 QAOA
  .yaspellerrc.json
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/qaoablock/ansats_types.png
  qmlcourseRU/_static/qaoablock/ansatz_mixing.png
  qmlcourseRU/_static/qaoablock/ansatz_operator_designation.png
  qmlcourseRU/_static/qaoablock/ansatz_sample.png
  qmlcourseRU/_static/qaoablock/general_scheme_for_n_qubits.png
  qmlcourseRU/_static/qaoablock/hamiltonian_u_phase.png
  qmlcourseRU/_static/qaoablock/the_1t_step_alg.png
  qmlcourseRU/_static/qaoablock/the_2d_step_alg.png
  qmlcourseRU/_static/qaoablock/the_3d_step_alg.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/qaoablock/intro.md
  qmlcourseRU/book/qaoablock/qaoa.md
Labels: lecture

#343 добавил авторов к лекциям
  .yaspellerrc.json
  qmlcourseRU/book/authors.md
  qmlcourseRU/book/dwaveblock/dwave.md
  qmlcourseRU/book/gradsblock/gradients.md
  qmlcourseRU/book/gradsblock/hogradients.md
  qmlcourseRU/book/hwblock/hwreview.md
  qmlcourseRU/book/hwblock/scqubits.md
  qmlcourseRU/book/intro1block/intro1.md
  qmlcourseRU/book/linalgblock/bra-ket.md
  qmlcourseRU/book/linalgblock/matrices.md
  qmlcourseRU/book/linalgblock/numpy.md
  qmlcourseRU/book/linalgblock/vectors.md
  qmlcourseRU/book/mlblock/ml_l1.md
  qmlcourseRU/book/problems2qml/eigenvals.md
  qmlcourseRU/book/problems2qml/jordanwigner.md
  qmlcourseRU/book/problems2qml/np2ising.md
  qmlcourseRU/book/problemsblock/advising.md
  qmlcourseRU/book/problemsblock/copt.md
  qmlcourseRU/book/problemsblock/ising.md
  qmlcourseRU/book/problemsblock/quantchemadvancedscf.md
  qmlcourseRU/book/problemsblock/quantchembasic.md
  qmlcourseRU/book/progblock/cirq_tfq.md
  qmlcourseRU/book/progblock/pennylane.md
  qmlcourseRU/book/progblock/progreview.md
  qmlcourseRU/book/progblock/qiskit.md
  qmlcourseRU/book/pythonblock/python_l1.md
  qmlcourseRU/book/pythonblock/python_l10.md
  qmlcourseRU/book/pythonblock/python_l2.md
  qmlcourseRU/book/pythonblock/python_l3.md
  qmlcourseRU/book/pythonblock/python_l4.md
  qmlcourseRU/book/pythonblock/python_l5.md
  qmlcourseRU/book/pythonblock/python_l6.md
  qmlcourseRU/book/pythonblock/python_l7.md
  qmlcourseRU/book/pythonblock/python_l8.md
  qmlcourseRU/book/pythonblock/python_l9.md
  qmlcourseRU/book/qaoablock/qaoa.md
  qmlcourseRU/book/qcalgo/deutschs_algorithm.md
  qmlcourseRU/book/qcalgo/grovers_algorithm.md
  qmlcourseRU/book/qcalgo/quantum_algorithms_overview.md
  qmlcourseRU/book/qcalgo/quantum_teleportation.md
  qmlcourseRU/book/qcalgo/simon_algorithm.md
  qmlcourseRU/book/qcalgo/superdense_coding.md
  qmlcourseRU/book/qcblock/gates.md
  qmlcourseRU/book/qcblock/mixedstates.md
  qmlcourseRU/book/qcblock/qubit.md
  qmlcourseRU/book/qmlkindsblock/hhl_algorithm.md
  qmlcourseRU/book/qmlkindsblock/qknn.md
  qmlcourseRU/book/qmlkindsblock/qmlkinds.md
  qmlcourseRU/book/qnnblock/qconv.md
  qmlcourseRU/book/qnnblock/qnn.md
  qmlcourseRU/book/qsvmblock/classic_svm.md
  qmlcourseRU/book/qsvmblock/hybridsvm.md
  qmlcourseRU/book/vqcblock/vqc.md
  qmlcourseRU/book/vqeblock/tspvqe.md
  qmlcourseRU/book/vqeblock/vqe.md
Labels: enhancement

#357 upgrade Pennylane to 0.20.0, draw circuits
  poetry.lock
  pyproject.toml
  qmlcourseRU/book/dwaveblock/dwave.md
  qmlcourseRU/book/progblock/pennylane.md
  qmlcourseRU/book/progblock/progreview.md
  qmlcourseRU/book/qcalgo/deutschs_algorithm.md
  qmlcourseRU/book/vqcblock/vqc.md
Labels: enhancement
