Repository quantum-ods/qmlcourse, pull requests merged in 2021-10, with the labels that each got.

#244 a minor note on the Hadamard gate
  qmlcourseRU/book/qcblock/qubit.md
Labels: minor_fix

#243 Update matrices.md
  qmlcourseRU/book/linalgblock/matrices.md
Labels: minor_fix

#245 try install tfq
  .github/workflows/deploy-book.yml
Labels: bug, ci

#246 Update Progsblock
  .yaspellerrc.json
  poetry.lock
  pyproject.toml
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/index/program.plantuml
  qmlcourseRU/_static/index/program.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/progblock/cirq_tfq.md
  qmlcourseRU/book/progblock/progreview.md
  qmlcourseRU/book/progblock/qiskit.md
Labels: lecture

#188 Mixedstates
  .yaspellerrc.json
  qmlcourseRU/_bibliography/references.bib
  qmlcourseRU/_static/qcblock/mixedstates/Landau.jpg
  qmlcourseRU/_static/qcblock/mixedstates/MarginalDistribution.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/gradsblock/gradients.md
  qmlcourseRU/book/qcblock/mixedstates.md
Labels: lecture
