Repository quantum-ods/qmlcourse, pull requests merged in 2021-08, with the labels that each got.

#119 Обновление README
  README.md
Labels: documentation, enhancement

#118 Added spell checker
  .github/problem-matchers/check-directory-tree.json
  .github/problem-matchers/editor-config.json
  .github/problem-matchers/yaspeller.json
  .github/workflows/book-check-text.yml
  .yaspellerrc.json
  tools/check_directory_tree.sh
Labels: ci, enhancement

#117 Вводная лекция по ML
  qmlcourseRU/_config.yml
  qmlcourseRU/_static/mlblock/covid_detection_ct.png
  qmlcourseRU/_static/mlblock/covid_detection_prediction.png
  qmlcourseRU/_static/mlblock/detection_yolo.jpeg
  qmlcourseRU/_static/mlblock/example_styletransfer.png
  qmlcourseRU/_static/mlblock/k_fold_cross_validation.png
  qmlcourseRU/_static/mlblock/object_detection_loss.png
  qmlcourseRU/_static/mlblock/see_also.png
  qmlcourseRU/_static/mlblock/vqgan_clip_quantum_mind.png
  qmlcourseRU/_static/qmlcourse_favicon.ico
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/mlblock/ml_intro.md
  qmlcourseRU/book/mlblock/ml_l1.md
Labels: enhancement, lecture

#134 Белый -> голубой в программе курса и иконках
  README.md
  qmlcourseRU/_config.yml
  qmlcourseRU/_static/index/program.plantuml
  qmlcourseRU/_static/index/program.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/index.md
Labels: enhancement

#147 python lec10 about OOP
  qmlcourseRU/_static/pythonblock/oop_l10/class_and_obj1.png
  qmlcourseRU/_static/pythonblock/oop_l10/class_and_obj_house.png
  qmlcourseRU/_static/pythonblock/oop_l10/class_and_obj_pika.png
  qmlcourseRU/_toc.yml
  qmlcourseRU/book/pythonblock/python_l10.md
Labels: lecture
